### PR TITLE
Update lastpass_creds module

### PR DESCRIPTION
**Pull request by wchen-r7**
Could you please test this? I hope I didn't break anything.

### CODE REVIEW

**Comment by wchen-r7** [comment]
> Why did you update the file name? In my tests, Firefox was adding .act to the file name. Did you see a different behavior?

Yeah, sorry, I actually do not have this file on my test box. So I thought `.act` was added by mistake.

screen shot 2016-01-21 at 1 24 20 pm

I can add that back, but if that is the file the module should read, it won't be able to find it on my box. Please let me know how you'd like to proceed.

**Comment by martinvigo** [comment]
Any updates @wchen-r7? As I explained above, .act is only for Firefox, IE will read the file without .act which is also the file you have. If you set it back to how it was and also move the check to verify the first iteration (respect to my other comment) I think we should be good and I will do some tests to make sure nothing broke with your enhancements. Thanks!

**Comment by wchen-r7** [comment]
@martinvigo Ok I will do that. Thanks.

**Comment by martinvigo** [comment]
Thanks @wchen-r7! I am currently on holidays but I am back next week and will test your changes and accept the PR if all looks good. I'll keep you posted

**Comment by wchen-r7** [comment]
Thanks!

**Comment by martinvigo** [comment]
Looks good! Is there any other improvements you want to add or you think it is ready now?

**Pull request merged**
